CREATE TABLE EMPLEADO
(
    IDEMPLEADO NUMBER(10) NOT NULL,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    CEDULA VARCHAR2(10) NOT NULL,
    ESTADO_CIVIL VARCHAR2(1) NOT NULL,
    GENERO VARCHAR2(1) NOT NULL,
    EDAD NUMBER(3) NOT NULL
)

ALTER TABLE EMPLEADO ADD CONSTRAINT ID_EMPLEADO_PK PRIMARY KEY (IDEMPLEADO);

 